Publish docs
seasalt-ai/docs-dev pull request #5
Opened 2022-01-13 04:42 UTC by Rulisetiawati

2022-01-13 05:58 UTC, xuchen requested changes
whats `objects.inv`?

also please:
1. address merge conflict
2. double check final output before you assign a reviewer

![image](https://user-images.githubusercontent.com/543547/149274068-b8964a04-6ca4-49e8-9d2a-5b9f1d8dff1c.png)

2022-01-14 01:24 UTC, KimDodds25 commented
Is this PR related? https://github.com/seasalt-ai/ngChat/pull/3843
Should you merge ^ that one first to have it included in the published version?

2022-01-14 22:52 UTC, xuchen requested changes
there's still trace of merge conflict in the generated docs.

2022-01-15 00:48 UTC, xuchen approved these changes

2022-01-18 06:19 UTC, merged